[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sspd"
version = "2.1.1-SNAPSHOT"
description = "SSH/SCP Project Delivery"
readme = "README.md"
authors = [
    { name = "homer", email = "mdfilippov_2@edu.hse.ru" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    'paramiko==5.0.0',
    'pathspec==1.1.1',
]

[project.urls]
GitHub = "https://github.com/MatveyFilippov/SSPD"

[tool.setuptools]
packages = { find = {} }

# pip install -U build
# python -m build