[build-system]
requires = ["hatchling>=1.0.0"]
build-backend = "hatchling.build"

[project]
name = "sspd"
version = "3.0.0dev2"
description = "SSH/SFTP Project Delivery"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "homer", email = "matdufi2004@gmail.com" }
]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "paramiko~=5.0",
    "pathspec~=1.1",
    "click~=8.5",
]

[project.urls]
GitHub = "https://github.com/MatveyFilippov/SSPD"

[tool.hatch.build.targets.wheel]
packages = ["src/sspd"]
