[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sspd"
version = "2.0.0"
description = "SSH/SCP Project Delivery"
readme = "README.md"
authors = [
    { name = "Homer", email = "mdfilippov_2@edu.hse.ru" }
]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    'paramiko==4.0.0',
]

[project.urls]
GitHub = "https://github.com/MatveyFilippov/SSPD"

[tool.setuptools]
packages = { find = {} }

# python -m build